name: Tauri Build and Release with Windows

on:
  push:
    branches:
      - main # 触发构建的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Node.js 版本
      - name: Setup Node.js v20.18.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 缓存 pnpm 依赖（可选）
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/AppData/Local/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 安装 Rust 工具链
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          components: rustfmt, clippy

      # 构建 Tauri 应用
      - name: Build Tauri app
        run: |
          pnpm run tauri build

      # 上传构建产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-windows
          path: |
            src-tauri/target/release/bundle/nsis/
